services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 1s
      timeout: 5s
      retries: 10
  
  # Static object storage 
  static:
    image: minio/minio
    container_name: static_dev
    restart: always
    volumes:
      - static-data:/data
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      db:
        condition: service_started
      static:
        condition: service_started
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - DATABASE_URL=${DATABASE_URL?Variable not set}
    ports:
      - 3000:3000

volumes:
  db-data:
    driver: local
  static-data:
    driver: local